name: build-pull-request
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'

      - run: mvn clean install