name: publish-master
run-name: Pull-request '${{ github.ref }}' was merged in master

on:
  push:
    branches:
      - TEOTB-16-dev-tech-debt-2

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -f telegram-bot-step-father/pom.xml

      - name: Get current version
        id: get-current-version
        run: |
          echo "PROJECT_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Update patch version
        run: mvn versions:set -f telegram-bot-step-father/pom.xml -DnewVersion=${{ steps.get-current-version.outputs.PROJECT_VERSION }} -DgenerateBackupPoms=false -DupdateChildModules=true

      #- name: Commit changes to master
      #  uses: actions-js/push@master
      #  with:
      #    github_token: ${{ github.token }}

      #- name: Publish to GitHub Packages
      #  run: mvn --file telegram-bot-step-father/pom.xml --batch-mode deploy
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}

      #- name: Delete Branch
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ github.token }}
      #    branch: ${{ github.ref }}
      #    force: true