name: publish-master
run-name: Pull-request '${{ github.event.pull_request.head.ref }}' was merged in master

on:
  push:
    branches:
      - kenny

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -f telegram-bot-step-father/pom.xml

      - name: Get current full version
        id: get-current-full-version
        run: |
          echo "PROJECT_MAJOR_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.major.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "PROJECT_MINOR_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.minor.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "PROJECT_PATCH_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.patch.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Increment patch version
        id: increment-patch-version
        run: echo "NEW_PROJECT_PATCH_VERSION=$((${{ steps.get-current-full-version.outputs.PROJECT_PATCH_VERSION }} + 1))" >> $GITHUB_OUTPUT

      - name: Update patch version in pom
        run: mvn versions:set-property -Dproperty=project.patch.version -DnewVersion=${{ steps.increment-patch-version.outputs.NEW_PROJECT_PATCH_VERSION }} -DupdatePomFile=true -DgenerateBackupPoms=false -f telegram-bot-step-father/pom.xml

      - name: Generate new full version
        id: get-new-full-version
        run: echo "NEW_PROJECT_VERSION=${{ steps.get-current-full-version.outputs.PROJECT_MAJOR_VERSION }}.${{ steps.get-current-full-version.outputs.PROJECT_MINOR_VERSION }}.${{ steps.increment-patch-version.outputs.NEW_PROJECT_PATCH_VERSION }}" >> $GITHUB_OUTPUT

      - name: Update patch version
        run: mvn versions:set -f telegram-bot-step-father/pom.xml -DnewVersion=${{ steps.get-new-full-version.outputs.NEW_PROJECT_VERSION }}-SNAPSHOT -DgenerateBackupPoms=false -DupdateChildModules=true

      - name: Commit changes to master
        uses: actions-js/push@master
        with:
          github_token: ${{ github.token }}

      - name: Publish to GitHub Packages
        run: mvn --file telegram-bot-step-father/pom.xml --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}

      #- name: Delete Branch
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ github.token }}
      #    branch: ${{ github.ref }}
      #    force: true