name: publish-master
run-name: Pull-request '${{ github.head_ref }}' was merged in master

on:
  push:
    branches:
      - TEOTB-14-dev-ops-configure-github-actions-to-publish-package

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -f telegram-bot-step-father/pom.xml

      - name: Publish to GitHub Packages
        run: mvn --file telegram-bot-step-father/pom.xml --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}