name: publish-master
run-name: Pull-request '${{ github.event.pull_request.head.ref }}' was merged in master

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'kenny'
    
    steps:
      - name: Checks out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0 

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package -f telegram-bot-step-father/pom.xml

      - name: Get current full version
        id: get-current-full-version
        run: |
          echo "PROJECT_MAJOR_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.major.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "PROJECT_MINOR_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.minor.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "PROJECT_PATCH_VERSION=$(mvn help:evaluate -f telegram-bot-step-father/pom.xml -Dexpression=project.patch.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Increment patch version
        id: increment-patch-version
        run: echo "NEW_PROJECT_PATCH_VERSION=$((${{ steps.get-current-full-version.outputs.PROJECT_PATCH_VERSION }} + 1))" >> $GITHUB_OUTPUT

      - name: Update patch version in pom
        run: mvn versions:set-property -Dproperty=project.patch.version -DnewVersion=${{ steps.increment-patch-version.outputs.NEW_PROJECT_PATCH_VERSION }} -DupdatePomFile=true -DgenerateBackupPoms=false -f telegram-bot-step-father/pom.xml

      - name: Generate new full version
        id: get-new-full-version
        run: echo "NEW_PROJECT_VERSION=${{ steps.get-current-full-version.outputs.PROJECT_MAJOR_VERSION }}.${{ steps.get-current-full-version.outputs.PROJECT_MINOR_VERSION }}.${{ steps.increment-patch-version.outputs.NEW_PROJECT_PATCH_VERSION }}" >> $GITHUB_OUTPUT

      - name: Update patch version
        run: mvn versions:set -f telegram-bot-step-father/pom.xml -DnewVersion=${{ steps.get-new-full-version.outputs.NEW_PROJECT_VERSION }}-SNAPSHOT -DgenerateBackupPoms=false -DupdateChildModules=true

      - name: Push changes to master
        uses: actions-js/push@master
        with:
           github_token: ${{ secrets.PERSONAL_ACESS_TOKEN_DEPLOY }}
           branch: kenny
           message: 'update: Auto increment patch version - ${{ steps.get-new-full-version.outputs.NEW_PROJECT_VERSION }}'

      - name: Publish to GitHub Packages
        run: mvn --file telegram-bot-step-father/pom.xml --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACESS_TOKEN_DEPLOY }}

      - name: Delete Merged Branch
        uses: actions/github-script@v4
        with:
          script: |
            const github = require('@actions/github');

            const octokit = new github.GitHub('${{ secrets.PERSONAL_ACESS_TOKEN_DEPLOY }}');

            octokit.git.deleteRef({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              ref: '${{ github.event.pull_request.head.ref }}'
            });