name: publish-master
run-name: Pull-request '${{ github.head_ref }}' was merged in master

on:
  push:
    branches:
      - TEOTB-14-dev-ops-configure-github-actions-to-publish-package

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checks out repository
        uses: actions/checkout@v3

      - name: Setup Java JDK 19
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '19'
          distribution: 'temurin'
          java-package: 'jdk'
          cache: 'maven'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: GITHUB_USER_REF  # env variable name for username
          server-password: GITHUB_TOKEN_REF
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package -f telegram-bot-step-father/pom.xml

      - name: Publish to GitHub Packages
        run: mvn deploy -f telegram-bot-step-father/pom.xml -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_USER_REF: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN_REF: ${{ secrets.GIT_TOKEN }}